config/routes.rb
Rails.application.routes.draw do
  resources :quotes
  resources :ex_models
  resources :risk_by_brands
  resources :pages do 
    collection do
      get :home
    end
  end

  get "app\views\pages\account.html.erb", to: "pages#account", as: "account"

  root to: 'pages#home'
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/calculations.rb
class Calculations

    def self.totalpremium
        ExModel.maximum(:price)
      end


end

app/models/ex_model.rb
class ExModel < ApplicationRecord
  belongs_to :risk_by_brand
  has_many :quotes
end

app/models/quote.rb
class Quote < ApplicationRecord
  belongs_to :ex_model


 

end

app/models/risk_by_brand.rb
class RiskByBrand < ApplicationRecord
    has_many :ex_models
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
   
end

app/controllers/calculations_controller.rb
class CalculationsController < ApplicationController
    def index
      @premium_total = Calculations.totalpremium
    
    end
  
  end
  

app/controllers/ex_models_controller.rb
class ExModelsController < ApplicationController
  before_action :set_ex_model, only: [:show, :edit, :update, :destroy]

  # GET /ex_models
  # GET /ex_models.json
  def index
    @ex_models = ExModel.all
  end

  # GET /ex_models/1
  # GET /ex_models/1.json
  def show
  end

  # GET /ex_models/new
  def new
    @ex_model = ExModel.new
  end

  # GET /ex_models/1/edit
  def edit
  end

  # POST /ex_models
  # POST /ex_models.json
  def create
    @ex_model = ExModel.new(ex_model_params)

    respond_to do |format|
      if @ex_model.save
        format.html { redirect_to @ex_model, notice: 'Ex model was successfully created.' }
        format.json { render :show, status: :created, location: @ex_model }
      else
        format.html { render :new }
        format.json { render json: @ex_model.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ex_models/1
  # PATCH/PUT /ex_models/1.json
  def update
    respond_to do |format|
      if @ex_model.update(ex_model_params)
        format.html { redirect_to @ex_model, notice: 'Ex model was successfully updated.' }
        format.json { render :show, status: :ok, location: @ex_model }
      else
        format.html { render :edit }
        format.json { render json: @ex_model.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ex_models/1
  # DELETE /ex_models/1.json
  def destroy
    @ex_model.destroy
    respond_to do |format|
      format.html { redirect_to ex_models_url, notice: 'Ex model was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ex_model
      @ex_model = ExModel.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def ex_model_params
      params.require(:ex_model).permit(:brand, :model, :price, :risk_by_brand_id)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def home
    end

    def account
    end
  end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
  before_action :set_quote, only: [:show, :edit, :update, :destroy]

  # GET /quotes
  # GET /quotes.json
  def index
    @quotes = Quote.all
  
  end

  # GET /quotes/1
  # GET /quotes/1.json
  def show
  end

  # GET /quotes/new
  def new
    @quote = Quote.new
  end

  # GET /quotes/1/edit
  def edit
  end

  # POST /quotes
  # POST /quotes.json
  def create
    @quote = Quote.new(quote_params)

    respond_to do |format|
      if @quote.save
        format.html { redirect_to @quote, notice: 'Quote was successfully created.' }
        format.json { render :show, status: :created, location: @quote }
      else
        format.html { render :new }
        format.json { render json: @quote.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /quotes/1
  # PATCH/PUT /quotes/1.json
  def update
    respond_to do |format|
      if @quote.update(quote_params)
        format.html { redirect_to @quote, notice: 'Quote was successfully updated.' }
        format.json { render :show, status: :ok, location: @quote }
      else
        format.html { render :edit }
        format.json { render json: @quote.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /quotes/1
  # DELETE /quotes/1.json
  def destroy
    @quote.destroy
    respond_to do |format|
      format.html { redirect_to quotes_url, notice: 'Quote was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_quote
      @quote = Quote.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def quote_params
      params.require(:quote).permit(:premium, :ex_model_id)
    end
end

app/controllers/risk_by_brands_controller.rb
class RiskByBrandsController < ApplicationController
  before_action :set_risk_by_brand, only: [:show, :edit, :update, :destroy]

  # GET /risk_by_brands
  # GET /risk_by_brands.json
  def index
    @risk_by_brands = RiskByBrand.all
  end

  # GET /risk_by_brands/1
  # GET /risk_by_brands/1.json
  def show
  end

  # GET /risk_by_brands/new
  def new
    @risk_by_brand = RiskByBrand.new
  end

  # GET /risk_by_brands/1/edit
  def edit
  end

  # POST /risk_by_brands
  # POST /risk_by_brands.json
  def create
    @risk_by_brand = RiskByBrand.new(risk_by_brand_params)

    respond_to do |format|
      if @risk_by_brand.save
        format.html { redirect_to @risk_by_brand, notice: 'Risk by brand was successfully created.' }
        format.json { render :show, status: :created, location: @risk_by_brand }
      else
        format.html { render :new }
        format.json { render json: @risk_by_brand.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /risk_by_brands/1
  # PATCH/PUT /risk_by_brands/1.json
  def update
    respond_to do |format|
      if @risk_by_brand.update(risk_by_brand_params)
        format.html { redirect_to @risk_by_brand, notice: 'Risk by brand was successfully updated.' }
        format.json { render :show, status: :ok, location: @risk_by_brand }
      else
        format.html { render :edit }
        format.json { render json: @risk_by_brand.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /risk_by_brands/1
  # DELETE /risk_by_brands/1.json
  def destroy
    @risk_by_brand.destroy
    respond_to do |format|
      format.html { redirect_to risk_by_brands_url, notice: 'Risk by brand was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_risk_by_brand
      @risk_by_brand = RiskByBrand.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def risk_by_brand_params
      params.require(:risk_by_brand).permit(:brand, :screen_risk, :total_loss_risk, :battery_risk)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ex_models_helper.rb
module ExModelsHelper
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/helpers/risk_by_brands_helper.rb
module RiskByBrandsHelper
end

app/views/ex_models/_form.html.erb
<%= form_with(model: ex_model, local: true) do |form| %>
  <% if ex_model.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(ex_model.errors.count, "error") %> prohibited this ex_model from being saved:</h2>

      <ul>
        <% ex_model.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :brand %>
    <%= form.text_field :brand %>
  </div>

  <div class="field">
    <%= form.label :model %>
    <%= form.text_field :model %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price %>
  </div>

  <div class="field">
    <%= form.label :risk_by_brand_id %>
    <%= form.text_field :risk_by_brand_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/ex_models/edit.html.erb
<h1>Editing Ex Model</h1>

<%= render 'form', ex_model: @ex_model %>

<%= link_to 'Show', @ex_model %> |
<%= link_to 'Back', ex_models_path %>

app/views/ex_models/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Ex Models</h1>

<table>
  <thead>
    <tr>
      <th>Brand</th>
      <th>Model</th>
      <th>Price</th>
      <th>Risk by brand</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ex_models.each do |ex_model| %>
      <tr>
        <td><%= ex_model.brand %></td>
        <td><%= ex_model.model %></td>
        <td><%= ex_model.price %></td>
        <td><%= ex_model.risk_by_brand_id %></td>
        <td><%= link_to 'Show', ex_model %></td>
        <td><%= link_to 'Edit', edit_ex_model_path(ex_model) %></td>
        <td><%= link_to 'Destroy', ex_model, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ex Model', new_ex_model_path %>

app/views/ex_models/new.html.erb
<h1>New Ex Model</h1>

<%= render 'form', ex_model: @ex_model %>

<%= link_to 'Back', ex_models_path %>

app/views/ex_models/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Brand:</strong>
  <%= @ex_model.brand %>
</p>

<p>
  <strong>Model:</strong>
  <%= @ex_model.model %>
</p>

<p>
  <strong>Price:</strong>
  <%= @ex_model.price %>
</p>

<p>
  <strong>Risk by brand:</strong>
  <%= @ex_model.risk_by_brand_id %>
</p>

<%= link_to 'Edit', edit_ex_model_path(@ex_model) %> |
<%= link_to 'Back', ex_models_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AIG WeCover</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div id="appHeader">
      <div class="inline-div">
        <div class="left">
        <a class="leftLink" href="<%= home_pages_path %>"><h2 id="mainHeader"><%= image_tag "house.png", size: "20x20", :class => "style_image_left" %>Home</h1></div>
        </a>

        <div class="right">
        <a class="rightLink" href="<%= account_path %>"><h2 id="accountHeader"><%= image_tag "hamburger.png", size: "20x20", :class => "style_image"%> My Account</h2></div>
        </a>
    </div>
      
    </div>

    <%= yield %>
  </body>
</html>

app/views/pages/account.html.erb
<div class="myAccountHeader">
<h2>Account Information</h2>
</div>

app/views/pages/home.html.erb
<div class="homeHeader"><h2>Welcome to AIG WeCover, please click the 
link below to start calculating your quote.</h2></div>
<div class="homeButton">
<%= link_to 'New Quote', new_quote_path, :class => 'homeQuoteButton', style: "color: white;" %>
</div>

app/views/quotes/_form.html.erb
<%= form_with(model: quote, local: true) do |form| %>
  <% if quote.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(quote.errors.count, "error") %> prohibited this quote from being saved:</h2>

      <ul>
        <% quote.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <!-- <div class="field">
    <%= form.label :premium %>
    <%= form.text_field :premium %>
  </div> -->
<br>
  <div class="field">
    <%= form.label "Phone Model" %>
    <%= form.collection_select :ex_model_id, ExModel.all, :id, :model %>
  </div>
  <br>

<div class="buttons">
  <div class="actions">
    <%= form.submit "Submit", :class => 'submitButton' %>
  </div>

  <div class="custom">
    <%= button_tag "Custom Coverage", :type => 'button', :class => "customButton", :onclick => "redirectCustom()" %>
  </div>
</div>

  <div class="refuseLink">
  <p onclick="redirectPay()" style="font-size : 11px">No, I don't need coverage</p>
   <p onclick="redirectHelp()" style="font-size : 11px">Get Help</p>
  </div>
  
  <script>
  function redirectPay() {
    window.confirm("No coverage selected. You will be redirected to payment...");
  }

  function redirectHelp() {
    window.confirm("You will be redirected to a sales representative for assistance.");
  }

  function redirectCustom() {
    window.confirm("You will be redirected to custom coverage...");
  }
  </script>
<% end %>

app/views/quotes/edit.html.erb
<h1>Editing Quote</h1>

<%= render 'form', quote: @quote %>

<%= link_to 'Show', @quote %> |
<%= link_to 'Back', quotes_path %>

app/views/quotes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Quotes</h1>

<table>
  <thead>
    <tr>
      <th>Premium</th>
      <th>Ex model</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @quotes.each do |quote| %>
      <tr>
        <td><%= quote.premium %></td>
        <td><%= quote.ex_model_id %></td>
        <td><%= link_to 'Show', quote %></td>
        <td><%= link_to 'Edit', edit_quote_path(quote) %></td>
        <td><%= link_to 'Destroy', quote, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Quote', new_quote_path %>

app/views/quotes/new.html.erb
<%= image_tag "cart.png", size: "80x108", :onclick => 'alert("You will be redirected to your cart...")', :class => "style_cart_image" %>


<%= image_tag "pay.png", size: "80x108", :onclick => 'alert("You will be redirected to payment...")', :class => "style_pay_image" %>


<div class="headers">
<h1 id="physicianHeader">AIG WeCover</h1>
<h2 id="benefitsHeader">Benefits of Coverage</h2>
</div>
<div class="subtitleCoverage">
<p>Accidents happen. AIG WeCover can ease your mind about those unexpected moments by offering rapid repair or replacement for covered damages, 
so you (and your phone) can be back to normal as soon as possible. Coverage includes:
</p>
</div>
<hr>

<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
.collapsible {
  background-color: rgb(64,83,105);
  color: white;
  cursor: pointer;
  padding: 18px;
  width: 50%;
  border: none;
  outline: none;
  font-size: 15px;
}

.active, .collapsible:hover {
  background-color: #7f90a3;
}

.content {
  padding: 0;
  display: none;
  overflow: hidden;
  width: 50%;
  margin-right: auto;
  margin-left: auto;
  background-color: #f1f1f1;
}

#collapsibles{
  text-align: center;
}

.collapsible:after {
  content: "＋"; /* Unicode character for "plus" sign (+) */
  font-size: 13px;
  color: white;
  float: right;
}

.active:after {
  content: "−"; /* Unicode character for "minus" sign (-) */
}

</style>
</head>
<body>

<div id="collapsibles">
<button type="button" class="collapsible">Screen Replacements</button>
<div class="content">
  <p>Priority repair of broken screens at any approved repair location, with no additional out-of-pocket costs.</p>
</div>
<button type="button" class="collapsible">Battery Replacements</button>
<div class="content">
  <p>If the phone battery fails unexpectedly or drops below acceptable battery health levels, WeCover will provide a replacement.</p>
</div>
<button type="button" class="collapsible">Total Loss</button>
<div class="content">
  <p>This inclusive option covers replacement for theft, extensive water damage, internal failure, and more. A replacement phone will be express shipped to your doorstep.</p>
</div>
</div>

<script>
var coll = document.getElementsByClassName("collapsible");
var i;

for (i = 0; i < coll.length; i++) {
  coll[i].addEventListener("click", function() {
    this.classList.toggle("active");
    var content = this.nextElementSibling;
    if (content.style.display === "block") {
      content.style.display = "none";
    } else {
      content.style.display = "block";
    }
  });
}
</script>

</body>
</html>

<%= render 'form', quote: @quote %>

<%#= link_to 'Back', quotes_path %>

app/views/quotes/show.html.erb
<div class="results">
  <p class="resultShow">
    <h2 class="priceHeader">Your Annual Price:</h2>
    $<%= sql = "select round(((0.33 * e.price * r.screen_risk) + 
          (0.2 * e.price * r.battery_risk) + (1 * e.price * r.total_loss_risk)),2) AS premium 
          from ex_models e join risk_by_brands r 
          on e.risk_by_brand_id=r.id 
          join quotes q ON q.ex_model_id=e.id 
          order by q.created_at desc limit 1;"
  results = ActiveRecord::Base.connection.exec_query(sql).cast_values
  results = results.to_a
  results.join(', ') %>
  </p>


<!-- <p>
  <strong>Phone Model:</strong>
  <%= @quote.ex_model_id %>
</p> -->

<%#= link_to 'Edit', edit_quote_path(@quote) %> 
<%#= link_to 'Back', quotes_path %>
<%= link_to 'New Quote', :back, :class => 'backLink' %>
</div>

app/views/risk_by_brands/_form.html.erb
<%= form_with(model: risk_by_brand, local: true) do |form| %>
  <% if risk_by_brand.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(risk_by_brand.errors.count, "error") %> prohibited this risk_by_brand from being saved:</h2>

      <ul>
        <% risk_by_brand.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :brand %>
    <%= form.text_field :brand %>
  </div>

  <div class="field">
    <%= form.label :screen_risk %>
    <%= form.text_field :screen_risk %>
  </div>

  <div class="field">
    <%= form.label :total_loss_risk %>
    <%= form.text_field :total_loss_risk %>
  </div>

  <div class="field">
    <%= form.label :battery_risk %>
    <%= form.text_field :battery_risk %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/risk_by_brands/edit.html.erb
<h1>Editing Risk By Brand</h1>

<%= render 'form', risk_by_brand: @risk_by_brand %>

<%= link_to 'Show', @risk_by_brand %> |
<%= link_to 'Back', risk_by_brands_path %>

app/views/risk_by_brands/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Risk By Brands</h1>

<table>
  <thead>
    <tr>
      <th>Brand</th>
      <th>Screen risk</th>
      <th>Total loss risk</th>
      <th>Battery risk</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @risk_by_brands.each do |risk_by_brand| %>
      <tr>
        <td><%= risk_by_brand.brand %></td>
        <td><%= risk_by_brand.screen_risk %></td>
        <td><%= risk_by_brand.total_loss_risk %></td>
        <td><%= risk_by_brand.battery_risk %></td>
        <td><%= link_to 'Show', risk_by_brand %></td>
        <td><%= link_to 'Edit', edit_risk_by_brand_path(risk_by_brand) %></td>
        <td><%= link_to 'Destroy', risk_by_brand, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Risk By Brand', new_risk_by_brand_path %>

app/views/risk_by_brands/new.html.erb
<h1>New Risk By Brand</h1>

<%= render 'form', risk_by_brand: @risk_by_brand %>

<%= link_to 'Back', risk_by_brands_path %>

app/views/risk_by_brands/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Brand:</strong>
  <%= @risk_by_brand.brand %>
</p>

<p>
  <strong>Screen risk:</strong>
  <%= @risk_by_brand.screen_risk %>
</p>

<p>
  <strong>Total loss risk:</strong>
  <%= @risk_by_brand.total_loss_risk %>
</p>

<p>
  <strong>Battery risk:</strong>
  <%= @risk_by_brand.battery_risk %>
</p>

<%= link_to 'Edit', edit_risk_by_brand_path(@risk_by_brand) %> |
<%= link_to 'Back', risk_by_brands_path %>